name: Label
on:
  pull_request:
    types: [opened, reopened, synchronize, edited]
permissions:
  contents: read
jobs:
  update_release_draft:
    permissions:
      # write permission is required for autolabeler
      # otherwise, read permission is required at least
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
